---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'betterform'
  
Debug:
  friendly_error_httpcode: true

Director:
  rules:
    '': 'BetterFormController'
    'api//$action/$param_name/$param_value': 'BetterFormController'
    